# SLM with ultravox & llama3.1, trained wtih knowledge distillation.
exp_name: "ultravox-streaming-experiments"

# Make sure to accept the license agreement on huggingface hub
text_model: "meta-llama/Llama-3.2-1B-Instruct"
audio_model: "openai/whisper-small"

loss_config:
  # Choose from ["KL_Divergence", "CrossEntropy"], default is "KL_Divergence"
  loss_function: "KL_Divergence"

train_sets:
  - name: librispeech-clean-continuation
  - name: librispeech-other-continuation
  - name: peoplespeech-clean-continuation
    weight: 8
 

val_sets:
  - name: peoplespeech

batch_size: 24
max_steps: 500 # x8x24 = 2,764,800
